### ISSUE TITLE
Getting a Svelte file as an output

### ISSUE THREAD

**Issue by YogliB** [rollup/rollup-plugin-svelte#70] opened 2019-10-19 08:58 UTC
I want to use preprocessors in my components, the problem is that others consuming my components must set their build to handle the preprocessors, which complicates things.

Is there a way to get a preprocessed `svelte` file instead of a js bundle?

**Comment by Conduitry** [comment] 2019-10-19 11:26
Essentially a duplicate of https://github.com/sveltejs/component-template/issues/8 - I don't think this is something that this plugin should be responsible for, but it is something we should have some way of handling.

**Closed by Conduitry** 2019-10-19 11:26 UTC
